PiL0: /home/nirvash/Projects/PiL0/lexer.h File Reference
/home/nirvash/Projects/PiL0/lexer.h File Reference
Header-File for Token-Stream library.
Data Structures
struct list
Element-Structure which builds Token-Stream.
struct keyword
Keyword structure for storing initial keywords.
union _tag_list.__unnamed__
struct _token.__unnamed__.token
struct _number.__unnamed__.number
struct _word.__unnamed__.word
Enumerations
enum special_IDs { IDENTIFIER = 300, NUM }
identifier number for variables and numbers
Functions
void l_init (list *)
Initialize new token stream with NULL-Pointer.
int l_IsEmpty (list)
check if token stream is empty or not
void l_append (list *, char *, int *)
add new element to token stream
void l_remove (list *)
remove oldest element in stream
list l_top (list)
get the oldest element of stream
list l_last (list)
get the newest element of stream
list lexer (char *)
Function for lexical scanning...
int get_keyNUM (keyword *, char *)
Returns the number of keyword.
keyword * init_ReservedKeys (void)
creates an array of all keywords
Variables
struct _tag_list tag_list
dummy element to quit compiler
Detailed Description
Header-File for Token-Stream library.
Forwards the functions of the Token-Stream library to another file which includes this header file.
Definition in file lexer.h.
Data Structure Documentation
struct _tag_list
Element-Structure which builds Token-Stream.
One element can only contain one token, whereas each element is connected with its last and previous neighbour.
Definition at line 15 of file lexer.h.
Data Fields
union _tag_list __unnamed__
struct _tag_list * next pointer to next element
struct _tag_list * previous pointer to previous element
char type Token-Type.
struct keyword
Keyword structure for storing initial keywords.
Stores string and ID of the language keywords like DO, WHILE, IF, etc.
Definition at line 85 of file lexer.h.
Data Fields
int ID keyword identifier
char w keyword
union _tag_list.__unnamed__
Definition at line 24 of file lexer.h.
Data Fields
__unnamed__ number
__unnamed__ token
__unnamed__ word
struct _tag_list::_token.__unnamed__.token
Definition at line 30 of file lexer.h.
Data Fields
char t single character
struct _tag_list::_number.__unnamed__.number
Definition at line 39 of file lexer.h.
Data Fields
unsigned int ID number identifier
int n number
struct _tag_list::_word.__unnamed__.word
Definition at line 49 of file lexer.h.
Data Fields
unsigned int ID keyword / identifier identifier
char w keyword / identifer
Enumeration Type Documentation
enum special_IDs
identifier number for variables and numbers
identifying numbers start at 300. NOTE: If keywords exceds more than 44 words, than you have to increase this number
Enumerator:
IDENTIFIER
NUM
Definition at line 81 of file lexer.h.
                 {
  IDENTIFIER = 300, NUM
};
Function Documentation
int get_keyNUM (keyword * k, char * s)
Returns the number of keyword.
Checks if the given word is a keyword and returns its position number from the key_array
Parameters:
k array of keywords...
s string to be checked...
Returns:
int either position number of keyword or -1 if word is not stored in keyword array
Definition at line 186 of file lexer.c.
References keywords.
Referenced by lexer().
{
  int i = 0;
  for (i = 0; keywords[i] != NULL; i++)
    if (strcmp(k[i].w, s) == 0) return i;
  return -1;
}
keyword* init_ReservedKeys (void)
creates an array of all keywords
Returns:
keyword* pointer to keyword array
Definition at line 210 of file lexer.c.
References get_keySize(), keyword::ID, and keywords.
Referenced by lexer().
{
  keyword *resKeys = malloc(sizeof *resKeys * get_keySize());
  int i;
  for (i = 0; keywords[i] != NULL; i++) {
    strcpy(resKeys[i].w,keywords[i]);
    resKeys[i].ID = 256 + i;
  }
  return resKeys;
}
void l_append (list * l, char * t, int * n)
add new element to token stream
Parameters:
l pointer on last element of token stream
t symbol, keyword, identifier or number to generate new token of
n identifier number of keyword, identifier or number
Returns:
void
Definition at line 103 of file lexer.c.
References ERR_MEMORY, error(), l_IsEmpty(), list::next, NULL_POINTER, list::previous, and list::type.
Referenced by lexer().
{
  if (l == NULL) error(NULL_POINTER);
  struct _tag_list *el;
  if ((el = malloc(sizeof(list))) == NULL) error(ERR_MEMORY);
  if (isdigit(*t) > 0) {
    el->number.n = atoi(t);
    el->number.ID = *n;
    el->type = 'n';
  } else if (isalpha(*t) > 0) {
    strcpy(el->word.w, t);
    el->word.ID = *n;
    el->type = 'w';
  } else {
    el->token.t = *t;
    el->type = 't';
  }
  el->next = *l;
  el->previous = NULL;
  if (!l_IsEmpty(*l)) (*l)->previous = el;
  if (l_IsEmpty(*l)) head = el;
  *l = el;
}
void l_init (list * l)
Initialize new token stream with NULL-Pointer.
Parameters:
l pointer on beginning of new token stream
Returns:
void
Definition at line 80 of file lexer.c.
References error(), and NULL_POINTER.
Referenced by lexer().
                     {
  if (l == NULL) error(NULL_POINTER);
  *l = NULL;
}
int l_IsEmpty (list l)
check if token stream is empty or not
Parameters:
l pointer on token stream
Returns:
int value 1 or 0
Definition at line 91 of file lexer.c.
Referenced by l_append(), l_last(), l_remove(), and l_top().
                      {
  return l == NULL;
}
list l_last (list l)
get the newest element of stream
Parameters:
l pointer on last element of token stream
Returns:
list point to newest element
Definition at line 165 of file lexer.c.
References error(), l_IsEmpty(), and NULL_POINTER.
Referenced by lexer().
                    {
  if (l_IsEmpty(l)) error(NULL_POINTER);
  return l;
}
void l_remove (list * l)
remove oldest element in stream
Parameters:
l pointer on last element of token stream
Returns:
void
Definition at line 132 of file lexer.c.
References EMPTY_LIST, error(), l_IsEmpty(), list::next, NULL_POINTER, and list::previous.
                       {
  if (l == NULL) error(NULL_POINTER);
  if (l_IsEmpty(*l)) error(EMPTY_LIST);
  if (head == *l) {
    free(head);
    *l = NULL;
  } else {
  struct _tag_list *ptr;
  ptr = head->previous;
  ptr->next = NULL;
  head->previous = NULL;
  free(head);
  head = ptr;
  }
}
list l_top (list l)
get the oldest element of stream
Parameters:
l pointer on last element of token stream
Returns:
list pointer to oldest element
Definition at line 154 of file lexer.c.
References error(), head, l_IsEmpty(), and NULL_POINTER.
                   {
  if (l_IsEmpty(l)) error(NULL_POINTER);
  return head;
}
list lexer (char * raw_code)
Function for lexical scanning...
Reads input code and convert each element to one token / word / number and add it to the token stream
Parameters:
raw_code input source code...
Returns:
list token-stream
Definition at line 229 of file lexer.c.
References get_keyNUM(), IDENTIFIER, init_ReservedKeys(), l_append(), l_init(), l_last(), and NUM.
Referenced by main().
{
  keyword *reserved = init_ReservedKeys();
  list token_stream, tok;
  l_init(&token_stream);
  printf("\n%s\n\n", raw_code);
  int i;
  for (i = 0; i < strlen(raw_code); i++) {
    char w[20] = "";
    int j = 0, key_NUM, ident = IDENTIFIER;
    while (raw_code[i] < 33)
      i++;
    if (raw_code[i] == 61 && raw_code[i + 1] == 61) {
      key_NUM = get_keyNUM(reserved, "==");
      l_append(&token_stream, reserved[key_NUM].w, &reserved[key_NUM].ID);
      i++;
    }
    if (raw_code[i] == 60 && raw_code[i + 1] == 61) {
      key_NUM = get_keyNUM(reserved, "<=");
      l_append(&token_stream, reserved[key_NUM].w, &reserved[key_NUM].ID);
      i++;
    }
    if (raw_code[i] == 62 && raw_code[i + 1] == 61) {
      key_NUM = get_keyNUM(reserved, ">=");
      l_append(&token_stream, reserved[key_NUM].w, &reserved[key_NUM].ID);
      i++;
    }
    if (raw_code[i] == 33 && raw_code[i + 1] == 61) {
      key_NUM = get_keyNUM(reserved, "!=");
      l_append(&token_stream, reserved[key_NUM].w, &reserved[key_NUM].ID);
      i++;
    }
    if (isalpha(raw_code[i])) {
      do {
        w[j] = raw_code[i];
        j++;
        i++;
      } while (isalnum(raw_code[i]));
      key_NUM = get_keyNUM(reserved, w);
      if (key_NUM >= 0) l_append(&token_stream, reserved[key_NUM].w, &reserved[key_NUM].ID);
      else l_append(&token_stream, w, &ident);
    }
    ident = NUM;
    if (isdigit(raw_code[i])) {
      do {
        w[j] = raw_code[i];
        j++;
        i++;
      } while (isdigit(raw_code[i]));
      l_append(&token_stream, w, &ident);
    }
    if (strlen(w) > 0) i--;
    else l_append(&token_stream, &raw_code[i], &ident);
    tok = l_last(token_stream);
    switch(tok->type) {
      case 't': printf("Token: %c\n", tok->token.t);
                break;
      case 'w': printf("Word: %s, %d\n", tok->word.w, tok->word.ID);
                break;
      case 'n': printf("Number: %d, %d\n", tok->number.n, tok->number.ID);
                break;
    }
  }
  return token_stream;
}
Variable Documentation
struct _tag_list tag_list
dummy element to quit compiler