PiL0: /home/nirvash/Projects/PiL0/lexer.c File Reference
/home/nirvash/Projects/PiL0/lexer.c File Reference
Library for Token-Stream.
#include "lexer.h"
#include "language.h"
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
Enumerations
enum err_codes { NULL_POINTER, ERR_MEMORY, EMPTY_LIST }
short strings used as variables for error messages
Functions
static void error (enum err_codes msg_nr)
Print error message.
void l_init (list *l)
Initialize new token stream with NULL-Pointer.
int l_IsEmpty (list l)
check if token stream is empty or not
void l_append (list *l, char *t, int *n)
add new element to token stream
void l_remove (list *l)
remove oldest element in stream
list l_top (list l)
get the oldest element of stream
list l_last (list l)
get the newest element of stream
int get_keyNUM (keyword *k, char *s)
Returns the number of keyword.
static unsigned int get_keySize ()
counts of keywords
keyword * init_ReservedKeys ()
creates an array of all keywords
list lexer (char *raw_code)
Function for lexical scanning...
Variables
static char * err_msg []
Stringtable which stores all error messages.
struct _tag_list * head
pointer to oldest element in stream
Detailed Description
Library for Token-Stream.
Contains data structures and functions to implement a linear token stream.
Error handling ensures that on wrong behaviour a message will be print what went wrong.
With the functions in this file new Tokens can be created and connected to each other, so they represent an FIFO (new elements will be added at the end of the stream, whereas the oldest element in the stream will be deketed from the top of the stream). Also there are functions to read the newest and oldest element of the stream.
Further functions are included to initalise the keywords with unique identifiers. The lexer scans the input file and creates a new token with the data he gets from the fitting keyword. if no keyword matches the input string must either be a token (non alphanumerical), a number or an identifier.
Definition in file lexer.c.
Enumeration Type Documentation
enum err_codes
short strings used as variables for error messages
Enumerator:
NULL_POINTER
ERR_MEMORY
EMPTY_LIST
Definition at line 46 of file lexer.c.
               {
    NULL_POINTER, ERR_MEMORY, EMPTY_LIST
  };
Function Documentation
static void error (enum err_codes msg_nr) [static]
Print error message.
Parameters:
msg_nr short string of the error message to print
Returns:
void
Definition at line 56 of file lexer.c.
References err_msg.
Referenced by l_append(), l_init(), l_last(), l_remove(), and l_top().
{
  fprintf(stderr, "FEHLER(intlist): %s!\n", err_msg[msg_nr]);
  exit(10);
}
int get_keyNUM (keyword * k, char * s)
Returns the number of keyword.
Checks if the given word is a keyword and returns its position number from the key_array
Parameters:
k array of keywords...
s string to be checked...
Returns:
int either position number of keyword or -1 if word is not stored in keyword array
Definition at line 186 of file lexer.c.
References keywords.
Referenced by lexer().
{
  int i = 0;
  for (i = 0; keywords[i] != NULL; i++)
    if (strcmp(k[i].w, s) == 0) return i;
  return -1;
}
static unsigned int get_keySize () [static]
counts of keywords
Returns:
unsigned int number of keywords
Definition at line 198 of file lexer.c.
References keywords.
Referenced by init_ReservedKeys().
{
  int i = 1;
  while (keywords[i] != NULL)
    i++;
  return i;
}
keyword* init_ReservedKeys (void)
creates an array of all keywords
Returns:
keyword* pointer to keyword array
Definition at line 210 of file lexer.c.
References get_keySize(), keyword::ID, and keywords.
Referenced by lexer().
{
  keyword *resKeys = malloc(sizeof *resKeys * get_keySize());
  int i;
  for (i = 0; keywords[i] != NULL; i++) {
    strcpy(resKeys[i].w,keywords[i]);
    resKeys[i].ID = 256 + i;
  }
  return resKeys;
}
void l_append (list * l, char * t, int * n)
add new element to token stream
Parameters:
l pointer on last element of token stream
t symbol, keyword, identifier or number to generate new token of
n identifier number of keyword, identifier or number
Returns:
void
Definition at line 103 of file lexer.c.
References ERR_MEMORY, error(), l_IsEmpty(), list::next, NULL_POINTER, list::previous, and list::type.
Referenced by lexer().
{
  if (l == NULL) error(NULL_POINTER);
  struct _tag_list *el;
  if ((el = malloc(sizeof(list))) == NULL) error(ERR_MEMORY);
  if (isdigit(*t) > 0) {
    el->number.n = atoi(t);
    el->number.ID = *n;
    el->type = 'n';
  } else if (isalpha(*t) > 0) {
    strcpy(el->word.w, t);
    el->word.ID = *n;
    el->type = 'w';
  } else {
    el->token.t = *t;
    el->type = 't';
  }
  el->next = *l;
  el->previous = NULL;
  if (!l_IsEmpty(*l)) (*l)->previous = el;
  if (l_IsEmpty(*l)) head = el;
  *l = el;
}
void l_init (list * l)
Initialize new token stream with NULL-Pointer.
Parameters:
l pointer on beginning of new token stream
Returns:
void
Definition at line 80 of file lexer.c.
References error(), and NULL_POINTER.
Referenced by lexer().
                     {
  if (l == NULL) error(NULL_POINTER);
  *l = NULL;
}
int l_IsEmpty (list l)
check if token stream is empty or not
Parameters:
l pointer on token stream
Returns:
int value 1 or 0
Definition at line 91 of file lexer.c.
Referenced by l_append(), l_last(), l_remove(), and l_top().
                      {
  return l == NULL;
}
list l_last (list l)
get the newest element of stream
Parameters:
l pointer on last element of token stream
Returns:
list point to newest element
Definition at line 165 of file lexer.c.
References error(), l_IsEmpty(), and NULL_POINTER.
Referenced by lexer().
                    {
  if (l_IsEmpty(l)) error(NULL_POINTER);
  return l;
}
void l_remove (list * l)
remove oldest element in stream
Parameters:
l pointer on last element of token stream
Returns:
void
Definition at line 132 of file lexer.c.
References EMPTY_LIST, error(), l_IsEmpty(), list::next, NULL_POINTER, and list::previous.
                       {
  if (l == NULL) error(NULL_POINTER);
  if (l_IsEmpty(*l)) error(EMPTY_LIST);
  if (head == *l) {
    free(head);
    *l = NULL;
  } else {
  struct _tag_list *ptr;
  ptr = head->previous;
  ptr->next = NULL;
  head->previous = NULL;
  free(head);
  head = ptr;
  }
}
list l_top (list l)
get the oldest element of stream
Parameters:
l pointer on last element of token stream
Returns:
list pointer to oldest element
Definition at line 154 of file lexer.c.
References error(), head, l_IsEmpty(), and NULL_POINTER.
                   {
  if (l_IsEmpty(l)) error(NULL_POINTER);
  return head;
}
list lexer (char * raw_code)
Function for lexical scanning...
Reads input code and convert each element to one token / word / number and add it to the token stream
Parameters:
raw_code input source code...
Returns:
list token-stream
Definition at line 229 of file lexer.c.
References get_keyNUM(), IDENTIFIER, init_ReservedKeys(), l_append(), l_init(), l_last(), and NUM.
Referenced by main().
{
  keyword *reserved = init_ReservedKeys();
  list token_stream, tok;
  l_init(&token_stream);
  printf("\n%s\n\n", raw_code);
  int i;
  for (i = 0; i < strlen(raw_code); i++) {
    char w[20] = "";
    int j = 0, key_NUM, ident = IDENTIFIER;
    while (raw_code[i] < 33)
      i++;
    if (raw_code[i] == 61 && raw_code[i + 1] == 61) {
      key_NUM = get_keyNUM(reserved, "==");
      l_append(&token_stream, reserved[key_NUM].w, &reserved[key_NUM].ID);
      i++;
    }
    if (raw_code[i] == 60 && raw_code[i + 1] == 61) {
      key_NUM = get_keyNUM(reserved, "<=");
      l_append(&token_stream, reserved[key_NUM].w, &reserved[key_NUM].ID);
      i++;
    }
    if (raw_code[i] == 62 && raw_code[i + 1] == 61) {
      key_NUM = get_keyNUM(reserved, ">=");
      l_append(&token_stream, reserved[key_NUM].w, &reserved[key_NUM].ID);
      i++;
    }
    if (raw_code[i] == 33 && raw_code[i + 1] == 61) {
      key_NUM = get_keyNUM(reserved, "!=");
      l_append(&token_stream, reserved[key_NUM].w, &reserved[key_NUM].ID);
      i++;
    }
    if (isalpha(raw_code[i])) {
      do {
        w[j] = raw_code[i];
        j++;
        i++;
      } while (isalnum(raw_code[i]));
      key_NUM = get_keyNUM(reserved, w);
      if (key_NUM >= 0) l_append(&token_stream, reserved[key_NUM].w, &reserved[key_NUM].ID);
      else l_append(&token_stream, w, &ident);
    }
    ident = NUM;
    if (isdigit(raw_code[i])) {
      do {
        w[j] = raw_code[i];
        j++;
        i++;
      } while (isdigit(raw_code[i]));
      l_append(&token_stream, w, &ident);
    }
    if (strlen(w) > 0) i--;
    else l_append(&token_stream, &raw_code[i], &ident);
    tok = l_last(token_stream);
    switch(tok->type) {
      case 't': printf("Token: %c\n", tok->token.t);
                break;
      case 'w': printf("Word: %s, %d\n", tok->word.w, tok->word.ID);
                break;
      case 'n': printf("Number: %d, %d\n", tok->number.n, tok->number.ID);
                break;
    }
  }
  return token_stream;
}
Variable Documentation
char * err_msg[] [static]
Initial value:
 {
    "Null-Pointer", "Kein Speicher frei",
    "Liste ist leer"
  }
Stringtable which stores all error messages.
Definition at line 38 of file lexer.c.
Referenced by error().
struct _tag_list * head
pointer to oldest element in stream
Definition at line 72 of file lexer.c.
Referenced by l_top().