PiL0: /home/nirvash/Projects/PiL0/tokdef.c File Reference
/home/nirvash/Projects/PiL0/tokdef.c File Reference
Library for Token-Stream.
#include "tokdef.h"
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
Enumerations
enum err_codes { NULL_POINTER, ERR_MEMORY, EMPTY_LIST }
short strings used as variables for error messages
enum id {
BEGIN = 256, CALL, CONST, DO,
END, IF, ODD, PRINT,
PROCEDURE, READ, THEN, VAR,
WHILE, PASS, EQ, GE,
LE, NE, IDENTIFIER, NUM
}
identifier number for every keyword longer than 1 character, identifier and number
Functions
static void error (enum err_codes msg_nr)
Print error message.
void l_init (list *l)
Initialize new token stream with NULL-Pointer.
int l_IsEmpty (list l)
check if token stream is empty or not
void l_append (list *l, char *t, int *n)
add new element to token stream
void l_remove (list *l)
remove oldest element in stream
list l_top (list l)
get the oldest element of stream
list l_last (list l)
get the newest element of stream
keyword * ini_BEGIN ()
initialise keyword BEGIN
keyword * ini_CALL ()
initialise keyword CALL
keyword * ini_CONST ()
initialise keyword CONST
keyword * ini_DO ()
initialise keyword DO
keyword * ini_END ()
initialise keyword END
keyword * ini_IF ()
initialise keyword IF
keyword * ini_ODD ()
initialise keyword ODD
keyword * ini_PRINT ()
initialise keyword PRINT
keyword * ini_PROCEDURE ()
initialise keyword PROCEDURE
keyword * ini_READ ()
initialise keyword READ
keyword * ini_THEN ()
initialise keyword THEN
keyword * ini_VAR ()
initialise keyword VAR
keyword * ini_WHILE ()
initialise keyword WHILE
keyword * ini_PASS ()
initialise keyword PASS
keyword * ini_EQ ()
initialise keyword ==
keyword * ini_GE ()
initialise keyword >=
keyword * ini_LE ()
initialise keyword <=
keyword * ini_NE ()
initialise keyword !=
Variables
static char * err_msg []
Stringtable which stores all error messages.
struct _tag_list * head
pointer to oldest element in stream
char * keywords []
Stringtable of all keywords longer than 1 character.
Detailed Description
Library for Token-Stream.
Contains data structures and functions to implement a linear token stream.
Error handling ensures that on wrong behaviour a message will be print what went wrong.
With the functions in this file new Tokens can be created and connected to each other, so they represent an FIFO (new elements will be added at the end of the stream, whereas the oldest element in the stream will be deketed from the top of the stream). Also there are functions to read the newest and oldest element of the stream.
Further functions are included to initalise the keywords with unique identifiers. The lexer scans the input file and creates a new token with the data he gets from the fitting keyword. if no keyword matches the input string must either be a token (non alphanumerical), a number or an identifier.
Definition in file tokdef.c.
Enumeration Type Documentation
enum err_codes
short strings used as variables for error messages
Enumerator:
NULL_POINTER
ERR_MEMORY
EMPTY_LIST
Definition at line 45 of file tokdef.c.
               {
    NULL_POINTER, ERR_MEMORY, EMPTY_LIST
  };
enum id
identifier number for every keyword longer than 1 character, identifier and number
identifying numbers start with 256
Enumerator:
BEGIN
CALL
CONST
DO
END
IF
ODD
PRINT
PROCEDURE
READ
THEN
VAR
WHILE
PASS
EQ
GE
LE
NE
IDENTIFIER
NUM
Definition at line 189 of file tokdef.c.
        {
  BEGIN = 256, CALL, CONST, DO, END, IF, ODD, PRINT,
  PROCEDURE, READ, THEN, VAR, WHILE, PASS, EQ, GE, LE, NE, IDENTIFIER, NUM
};
Function Documentation
static void error (enum err_codes msg_nr) [static]
Print error message.
Parameters:
msg_nr short string of the error message to print
Returns:
void
Definition at line 55 of file tokdef.c.
References err_msg.
Referenced by ini_BEGIN(), ini_CALL(), ini_CONST(), ini_DO(), ini_END(), ini_EQ(), ini_GE(), ini_IF(), ini_LE(), ini_NE(), ini_ODD(), ini_PASS(), ini_PRINT(), ini_PROCEDURE(), ini_READ(), ini_THEN(), ini_VAR(), ini_WHILE(), l_append(), l_init(), l_last(), l_remove(), and l_top().
{
  fprintf(stderr, "FEHLER(intlist): %s!\n", err_msg[msg_nr]);
  exit(10);
}
keyword* ini_BEGIN ()
initialise keyword BEGIN
Returns:
keyword*
Definition at line 199 of file tokdef.c.
References BEGIN, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                     {
  keyword *BEGIN_PTR;
  if ((BEGIN_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(BEGIN_PTR->w, keywords[BEGIN - 256]);
  BEGIN_PTR->ID = BEGIN;
  return BEGIN_PTR;
}
keyword* ini_CALL ()
initialise keyword CALL
Returns:
keyword*
Definition at line 212 of file tokdef.c.
References CALL, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                    {
  keyword *CALL_PTR;
  if ((CALL_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(CALL_PTR->w, keywords[CALL - 256]);
  CALL_PTR->ID = CALL;
  return CALL_PTR;
}
keyword* ini_CONST ()
initialise keyword CONST
Returns:
keyword*
Definition at line 225 of file tokdef.c.
References CONST, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                     {
  keyword *CONST_PTR;
  if ((CONST_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(CONST_PTR->w, keywords[CONST - 256]);
  CONST_PTR->ID = CONST;
  return CONST_PTR;
}
keyword* ini_DO ()
initialise keyword DO
Returns:
keyword*
Definition at line 238 of file tokdef.c.
References DO, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                  {
  keyword *DO_PTR;
  if ((DO_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(DO_PTR->w, keywords[DO - 256]);
  DO_PTR->ID = DO;
  return DO_PTR;
}
keyword* ini_END ()
initialise keyword END
Returns:
keyword*
Definition at line 251 of file tokdef.c.
References END, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                   {
  keyword *END_PTR;
  if ((END_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(END_PTR->w, keywords[END - 256]);
  END_PTR->ID = END;
  return END_PTR;
}
keyword* ini_EQ ()
initialise keyword ==
Returns:
keyword*
Definition at line 381 of file tokdef.c.
References EQ, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                  {
  keyword *EQ_PTR;
  if ((EQ_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(EQ_PTR->w, keywords[EQ - 256]);
  EQ_PTR->ID = EQ;
  return EQ_PTR;
}
keyword* ini_GE ()
initialise keyword >=
Returns:
keyword*
Definition at line 394 of file tokdef.c.
References ERR_MEMORY, error(), GE, keyword::ID, keywords, and keyword::w.
                  {
  keyword *GE_PTR;
  if ((GE_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(GE_PTR->w, keywords[GE - 256]);
  GE_PTR->ID = GE;
  return GE_PTR;
}
keyword* ini_IF ()
initialise keyword IF
Returns:
keyword*
Definition at line 264 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, IF, keywords, and keyword::w.
                  {
  keyword *IF_PTR;
  if ((IF_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(IF_PTR->w, keywords[IF - 256]);
  IF_PTR->ID = IF;
  return IF_PTR;
}
keyword* ini_LE ()
initialise keyword <=
Returns:
keyword*
Definition at line 407 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, LE, and keyword::w.
                  {
  keyword *LE_PTR;
  if ((LE_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(LE_PTR->w, keywords[LE - 256]);
  LE_PTR->ID = LE;
  return LE_PTR;
}
keyword* ini_NE ()
initialise keyword !=
Returns:
keyword*
Definition at line 420 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, NE, and keyword::w.
                  {
  keyword *NE_PTR;
  if ((NE_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(NE_PTR->w, keywords[NE - 256]);
  NE_PTR->ID = NE;
  return NE_PTR;
}
keyword* ini_ODD ()
initialise keyword ODD
Returns:
keyword*
Definition at line 277 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, ODD, and keyword::w.
                   {
  keyword *ODD_PTR;
  if ((ODD_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(ODD_PTR->w, keywords[ODD - 256]);
  ODD_PTR->ID = ODD;
  return ODD_PTR;
}
keyword* ini_PASS ()
initialise keyword PASS
Returns:
keyword*
Definition at line 368 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, PASS, and keyword::w.
                    {
  keyword *PASS_PTR;
  if ((PASS_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(PASS_PTR->w, keywords[PASS - 256]);
  PASS_PTR->ID = PASS;
  return PASS_PTR;
}
keyword* ini_PRINT ()
initialise keyword PRINT
Returns:
keyword*
Definition at line 290 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, PRINT, and keyword::w.
                     {
  keyword *PRINT_PTR;
  if ((PRINT_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(PRINT_PTR->w, keywords[PRINT - 256]);
  PRINT_PTR->ID = PRINT;
  return PRINT_PTR;
}
keyword* ini_PROCEDURE ()
initialise keyword PROCEDURE
Returns:
keyword*
Definition at line 303 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, PROCEDURE, and keyword::w.
{
  keyword *PROCEDURE_PTR;
  if ((PROCEDURE_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(PROCEDURE_PTR->w, keywords[PROCEDURE - 256]);
  PROCEDURE_PTR->ID = PROCEDURE;
  return PROCEDURE_PTR;
}
keyword* ini_READ ()
initialise keyword READ
Returns:
keyword*
Definition at line 316 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, READ, and keyword::w.
                    {
  keyword *READ_PTR;
  if ((READ_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(READ_PTR->w, keywords[READ - 256]);
  READ_PTR->ID = READ;
  return READ_PTR;
}
keyword* ini_THEN ()
initialise keyword THEN
Returns:
keyword*
Definition at line 329 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, THEN, and keyword::w.
                    {
  keyword *THEN_PTR;
  if ((THEN_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(THEN_PTR->w, keywords[THEN - 256]);
  THEN_PTR->ID = THEN;
  return THEN_PTR;
}
keyword* ini_VAR ()
initialise keyword VAR
Returns:
keyword*
Definition at line 342 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, VAR, and keyword::w.
                   {
  keyword *VAR_PTR;
  if ((VAR_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(VAR_PTR->w, keywords[VAR - 256]);
  VAR_PTR->ID = VAR;
  return VAR_PTR;
}
keyword* ini_WHILE ()
initialise keyword WHILE
Returns:
keyword*
Definition at line 355 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, keyword::w, and WHILE.
                     {
  keyword *WHILE_PTR;
  if ((WHILE_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(WHILE_PTR->w, keywords[WHILE - 256]);
  WHILE_PTR->ID = WHILE;
  return WHILE_PTR;
}
void l_append (list * l, char * t, int * n)
add new element to token stream
Parameters:
l pointer on last element of token stream
t symbol, keyword, identifier or number to generate new token of
n identifier number of keyword, identifier or number
Returns:
void
Definition at line 102 of file tokdef.c.
References ERR_MEMORY, error(), l_IsEmpty(), list::next, NULL_POINTER, list::previous, and list::type.
{
  if (l == NULL) error(NULL_POINTER);
  struct _tag_list *el;
  if ((el = malloc(sizeof(list))) == NULL) error(ERR_MEMORY);
  if (strlen(t) == 1) {
    el->token.t = *t;
    el->type = 't';
  } else if (isdigit(*t) > 0) {
    el->number.n = atoi(t);
    el->number.ID = *n;
    el->type = 'n';
  } else {
    strcpy(el->word.w, t);
    el->word.ID = *n;
    el->type = 'w';
  }
  el->next = *l;
  el->previous = NULL;
  if (!l_IsEmpty(*l)) (*l)->previous = el;
  if (l_IsEmpty(*l)) head = el;
  *l = el;
}
void l_init (list * l)
Initialize new token stream with NULL-Pointer.
Parameters:
l pointer on beginning of new token stream
Returns:
void
Definition at line 79 of file tokdef.c.
References error(), and NULL_POINTER.
                     {
  if (l == NULL) error(NULL_POINTER);
  *l = NULL;
}
int l_IsEmpty (list l)
check if token stream is empty or not
Parameters:
l pointer on token stream
Returns:
int value 1 or 0
Definition at line 90 of file tokdef.c.
Referenced by l_append(), l_last(), l_remove(), and l_top().
                      {
  return l == NULL;
}
list l_last (list l)
get the newest element of stream
Parameters:
l pointer on last element of token stream
Returns:
list point to newest element
Definition at line 164 of file tokdef.c.
References error(), l_IsEmpty(), and NULL_POINTER.
                    {
  if (l_IsEmpty(l)) error(NULL_POINTER);
  return l;
}
void l_remove (list * l)
remove oldest element in stream
Parameters:
l pointer on last element of token stream
Returns:
void
Definition at line 131 of file tokdef.c.
References EMPTY_LIST, error(), l_IsEmpty(), list::next, NULL_POINTER, and list::previous.
                       {
  if (l == NULL) error(NULL_POINTER);
  if (l_IsEmpty(*l)) error(EMPTY_LIST);
  if (head == *l) {
    free(head);
    *l = NULL;
  } else {
  struct _tag_list *ptr;
  ptr = head->previous;
  ptr->next = NULL;
  head->previous = NULL;
  free(head);
  head = ptr;
  }
}
list l_top (list l)
get the oldest element of stream
Parameters:
l pointer on last element of token stream
Returns:
list pointer to oldest element
Definition at line 153 of file tokdef.c.
References error(), head, l_IsEmpty(), and NULL_POINTER.
                   {
  if (l_IsEmpty(l)) error(NULL_POINTER);
  return head;
}
Variable Documentation
char * err_msg[] [static]
Initial value:
 {
    "Null-Pointer", "Kein Speicher frei",
    "Liste ist leer"
  }
Stringtable which stores all error messages.
Definition at line 37 of file tokdef.c.
Referenced by error().
struct _tag_list * head
pointer to oldest element in stream
Definition at line 71 of file tokdef.c.
Referenced by l_top().
char * keywords[]
Initial value:
 {
  "BEGIN", "CALL", "CONST", "DO", "END", "IF", "ODD", "PRINT", "PROCEDURE",
  "READ", "THEN", "VAR", "WHILE", "PASS", "==", ">=", "<=", "!="
}
Stringtable of all keywords longer than 1 character.
Definition at line 179 of file tokdef.c.
Referenced by ini_BEGIN(), ini_CALL(), ini_CONST(), ini_DO(), ini_END(), ini_EQ(), ini_GE(), ini_IF(), ini_LE(), ini_NE(), ini_ODD(), ini_PASS(), ini_PRINT(), ini_PROCEDURE(), ini_READ(), ini_THEN(), ini_VAR(), and ini_WHILE().