PiL0: /home/nirvash/Projects/PiL0/tokdef.h File Reference
/home/nirvash/Projects/PiL0/tokdef.h File Reference
Header-File for Token-Stream library.
Data Structures
struct list
Element-Structure which builds Token-Stream.
struct keyword
Keyword structure for storing initial keywords.
union _tag_list.__unnamed__
struct _token.__unnamed__.token
struct _number.__unnamed__.number
struct _word.__unnamed__.word
Functions
void l_init (list *)
Initialize new token stream with NULL-Pointer.
int l_IsEmpty (list)
check if token stream is empty or not
void l_append (list *, char *, int *)
add new element to token stream
void l_remove (list *)
remove oldest element in stream
list l_top (list)
get the oldest element of stream
list l_last (list)
get the newest element of stream
keyword * ini_BEGIN ()
initialise keyword BEGIN
keyword * ini_CALL ()
initialise keyword CALL
keyword * ini_CONST ()
initialise keyword CONST
keyword * ini_DO ()
initialise keyword DO
keyword * ini_END ()
initialise keyword END
keyword * ini_IF ()
initialise keyword IF
keyword * ini_ODD ()
initialise keyword ODD
keyword * ini_PRINT ()
initialise keyword PRINT
keyword * ini_PROCEDURE ()
initialise keyword PROCEDURE
keyword * ini_READ ()
initialise keyword READ
keyword * ini_THEN ()
initialise keyword THEN
keyword * ini_VAR ()
initialise keyword VAR
keyword * ini_WHILE ()
initialise keyword WHILE
keyword * ini_PASS ()
initialise keyword PASS
keyword * ini_EQ ()
initialise keyword ==
keyword * ini_GE ()
initialise keyword >=
keyword * ini_LE ()
initialise keyword <=
keyword * ini_NE ()
initialise keyword !=
Variables
struct _tag_list tag_list
dummy element to quit compiler
Detailed Description
Header-File for Token-Stream library.
Forwards the functions of the Token-Stream library to another file which includes this header file.
Definition in file tokdef.h.
Data Structure Documentation
struct _tag_list
Element-Structure which builds Token-Stream.
One element can only contain one token, whereas each element is connected with its last and previous neighbour.
Definition at line 15 of file tokdef.h.
Data Fields
union _tag_list __unnamed__
struct _tag_list * next pointer to next element
struct _tag_list * previous pointer to previous element
char type Token-Type.
struct keyword
Keyword structure for storing initial keywords.
Stores string and ID of the language keywords like DO, WHILE, IF, etc.
Definition at line 66 of file tokdef.h.
Data Fields
int ID keyword identifier
char w keyword
union _tag_list.__unnamed__
Definition at line 24 of file tokdef.h.
Data Fields
__unnamed__ number
__unnamed__ token
__unnamed__ word
struct _tag_list::_token.__unnamed__.token
Definition at line 30 of file tokdef.h.
Data Fields
char t single character
struct _tag_list::_number.__unnamed__.number
Definition at line 39 of file tokdef.h.
Data Fields
unsigned int ID number identifier
int n number
struct _tag_list::_word.__unnamed__.word
Definition at line 49 of file tokdef.h.
Data Fields
unsigned int ID keyword / identifier identifier
char w keyword / identifer
Function Documentation
keyword* ini_BEGIN ()
initialise keyword BEGIN
Returns:
keyword*
Definition at line 199 of file tokdef.c.
References BEGIN, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                     {
  keyword *BEGIN_PTR;
  if ((BEGIN_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(BEGIN_PTR->w, keywords[BEGIN - 256]);
  BEGIN_PTR->ID = BEGIN;
  return BEGIN_PTR;
}
keyword* ini_CALL ()
initialise keyword CALL
Returns:
keyword*
Definition at line 212 of file tokdef.c.
References CALL, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                    {
  keyword *CALL_PTR;
  if ((CALL_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(CALL_PTR->w, keywords[CALL - 256]);
  CALL_PTR->ID = CALL;
  return CALL_PTR;
}
keyword* ini_CONST ()
initialise keyword CONST
Returns:
keyword*
Definition at line 225 of file tokdef.c.
References CONST, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                     {
  keyword *CONST_PTR;
  if ((CONST_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(CONST_PTR->w, keywords[CONST - 256]);
  CONST_PTR->ID = CONST;
  return CONST_PTR;
}
keyword* ini_DO ()
initialise keyword DO
Returns:
keyword*
Definition at line 238 of file tokdef.c.
References DO, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                  {
  keyword *DO_PTR;
  if ((DO_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(DO_PTR->w, keywords[DO - 256]);
  DO_PTR->ID = DO;
  return DO_PTR;
}
keyword* ini_END ()
initialise keyword END
Returns:
keyword*
Definition at line 251 of file tokdef.c.
References END, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                   {
  keyword *END_PTR;
  if ((END_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(END_PTR->w, keywords[END - 256]);
  END_PTR->ID = END;
  return END_PTR;
}
keyword* ini_EQ ()
initialise keyword ==
Returns:
keyword*
Definition at line 381 of file tokdef.c.
References EQ, ERR_MEMORY, error(), keyword::ID, keywords, and keyword::w.
                  {
  keyword *EQ_PTR;
  if ((EQ_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(EQ_PTR->w, keywords[EQ - 256]);
  EQ_PTR->ID = EQ;
  return EQ_PTR;
}
keyword* ini_GE ()
initialise keyword >=
Returns:
keyword*
Definition at line 394 of file tokdef.c.
References ERR_MEMORY, error(), GE, keyword::ID, keywords, and keyword::w.
                  {
  keyword *GE_PTR;
  if ((GE_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(GE_PTR->w, keywords[GE - 256]);
  GE_PTR->ID = GE;
  return GE_PTR;
}
keyword* ini_IF ()
initialise keyword IF
Returns:
keyword*
Definition at line 264 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, IF, keywords, and keyword::w.
                  {
  keyword *IF_PTR;
  if ((IF_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(IF_PTR->w, keywords[IF - 256]);
  IF_PTR->ID = IF;
  return IF_PTR;
}
keyword* ini_LE ()
initialise keyword <=
Returns:
keyword*
Definition at line 407 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, LE, and keyword::w.
                  {
  keyword *LE_PTR;
  if ((LE_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(LE_PTR->w, keywords[LE - 256]);
  LE_PTR->ID = LE;
  return LE_PTR;
}
keyword* ini_NE ()
initialise keyword !=
Returns:
keyword*
Definition at line 420 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, NE, and keyword::w.
                  {
  keyword *NE_PTR;
  if ((NE_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(NE_PTR->w, keywords[NE - 256]);
  NE_PTR->ID = NE;
  return NE_PTR;
}
keyword* ini_ODD ()
initialise keyword ODD
Returns:
keyword*
Definition at line 277 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, ODD, and keyword::w.
                   {
  keyword *ODD_PTR;
  if ((ODD_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(ODD_PTR->w, keywords[ODD - 256]);
  ODD_PTR->ID = ODD;
  return ODD_PTR;
}
keyword* ini_PASS ()
initialise keyword PASS
Returns:
keyword*
Definition at line 368 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, PASS, and keyword::w.
                    {
  keyword *PASS_PTR;
  if ((PASS_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(PASS_PTR->w, keywords[PASS - 256]);
  PASS_PTR->ID = PASS;
  return PASS_PTR;
}
keyword* ini_PRINT ()
initialise keyword PRINT
Returns:
keyword*
Definition at line 290 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, PRINT, and keyword::w.
                     {
  keyword *PRINT_PTR;
  if ((PRINT_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(PRINT_PTR->w, keywords[PRINT - 256]);
  PRINT_PTR->ID = PRINT;
  return PRINT_PTR;
}
keyword* ini_PROCEDURE ()
initialise keyword PROCEDURE
Returns:
keyword*
Definition at line 303 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, PROCEDURE, and keyword::w.
{
  keyword *PROCEDURE_PTR;
  if ((PROCEDURE_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(PROCEDURE_PTR->w, keywords[PROCEDURE - 256]);
  PROCEDURE_PTR->ID = PROCEDURE;
  return PROCEDURE_PTR;
}
keyword* ini_READ ()
initialise keyword READ
Returns:
keyword*
Definition at line 316 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, READ, and keyword::w.
                    {
  keyword *READ_PTR;
  if ((READ_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(READ_PTR->w, keywords[READ - 256]);
  READ_PTR->ID = READ;
  return READ_PTR;
}
keyword* ini_THEN ()
initialise keyword THEN
Returns:
keyword*
Definition at line 329 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, THEN, and keyword::w.
                    {
  keyword *THEN_PTR;
  if ((THEN_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(THEN_PTR->w, keywords[THEN - 256]);
  THEN_PTR->ID = THEN;
  return THEN_PTR;
}
keyword* ini_VAR ()
initialise keyword VAR
Returns:
keyword*
Definition at line 342 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, VAR, and keyword::w.
                   {
  keyword *VAR_PTR;
  if ((VAR_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(VAR_PTR->w, keywords[VAR - 256]);
  VAR_PTR->ID = VAR;
  return VAR_PTR;
}
keyword* ini_WHILE ()
initialise keyword WHILE
Returns:
keyword*
Definition at line 355 of file tokdef.c.
References ERR_MEMORY, error(), keyword::ID, keywords, keyword::w, and WHILE.
                     {
  keyword *WHILE_PTR;
  if ((WHILE_PTR = malloc(sizeof(keyword))) == NULL) error(ERR_MEMORY);
  strcpy(WHILE_PTR->w, keywords[WHILE - 256]);
  WHILE_PTR->ID = WHILE;
  return WHILE_PTR;
}
void l_append (list * l, char * t, int * n)
add new element to token stream
Parameters:
l pointer on last element of token stream
t symbol, keyword, identifier or number to generate new token of
n identifier number of keyword, identifier or number
Returns:
void
Definition at line 102 of file tokdef.c.
References ERR_MEMORY, error(), l_IsEmpty(), list::next, NULL_POINTER, list::previous, and list::type.
{
  if (l == NULL) error(NULL_POINTER);
  struct _tag_list *el;
  if ((el = malloc(sizeof(list))) == NULL) error(ERR_MEMORY);
  if (strlen(t) == 1) {
    el->token.t = *t;
    el->type = 't';
  } else if (isdigit(*t) > 0) {
    el->number.n = atoi(t);
    el->number.ID = *n;
    el->type = 'n';
  } else {
    strcpy(el->word.w, t);
    el->word.ID = *n;
    el->type = 'w';
  }
  el->next = *l;
  el->previous = NULL;
  if (!l_IsEmpty(*l)) (*l)->previous = el;
  if (l_IsEmpty(*l)) head = el;
  *l = el;
}
void l_init (list * l)
Initialize new token stream with NULL-Pointer.
Parameters:
l pointer on beginning of new token stream
Returns:
void
Definition at line 79 of file tokdef.c.
References error(), and NULL_POINTER.
                     {
  if (l == NULL) error(NULL_POINTER);
  *l = NULL;
}
int l_IsEmpty (list l)
check if token stream is empty or not
Parameters:
l pointer on token stream
Returns:
int value 1 or 0
Definition at line 90 of file tokdef.c.
Referenced by l_append(), l_last(), l_remove(), and l_top().
                      {
  return l == NULL;
}
list l_last (list l)
get the newest element of stream
Parameters:
l pointer on last element of token stream
Returns:
list point to newest element
Definition at line 164 of file tokdef.c.
References error(), l_IsEmpty(), and NULL_POINTER.
                    {
  if (l_IsEmpty(l)) error(NULL_POINTER);
  return l;
}
void l_remove (list * l)
remove oldest element in stream
Parameters:
l pointer on last element of token stream
Returns:
void
Definition at line 131 of file tokdef.c.
References EMPTY_LIST, error(), l_IsEmpty(), list::next, NULL_POINTER, and list::previous.
                       {
  if (l == NULL) error(NULL_POINTER);
  if (l_IsEmpty(*l)) error(EMPTY_LIST);
  if (head == *l) {
    free(head);
    *l = NULL;
  } else {
  struct _tag_list *ptr;
  ptr = head->previous;
  ptr->next = NULL;
  head->previous = NULL;
  free(head);
  head = ptr;
  }
}
list l_top (list l)
get the oldest element of stream
Parameters:
l pointer on last element of token stream
Returns:
list pointer to oldest element
Definition at line 153 of file tokdef.c.
References error(), head, l_IsEmpty(), and NULL_POINTER.
                   {
  if (l_IsEmpty(l)) error(NULL_POINTER);
  return head;
}
Variable Documentation
struct _tag_list tag_list
dummy element to quit compiler